[package]
name = "oxyd-core"
version = "0.1.0"
edition = "2024"

[dependencies]
oxyd-domain = { path = "../oxyd-domain" }  
oxyd-process-manager = { path = "../oxyd-process-manager" }
tokio = { workspace = true }
async-trait = { workspace = true }
